#!/bin/bash
#SBATCH --job-name ribomap
#SBATCH -o %J.sqanti3.out
#SBATCH -e %J.sqanti3.err  

######################################################################
# Running ribomap for RNA and ribosome profiling data integration
######################################################################
#
# This script integrates RNA-seq and ribosome profiling data using ribomap.
# It processes fastq files, aligns reads, and performs quantification.
# Ensure all dependencies are installed before running this script.
# Please ensure that you have the necessary dependencies installed before running this script.
# Author: Mahoko T. Ueda
# Date: March 27, 2024
#
#
###############################
# Set your parameters
###############################

max_jobs=5 #the maximum number of parallel jobs that can be run simultaneously
FILENAME=/path/to/the/directory/sample_name.txt

while read LINE;do
     fastq=/path/to/the/fastq/directory/${LINE}
     echo ${LINE}
	 
     run_ribomap.sh \
	    --rnaseq_fq "${fastq}_1.fastq.gz" "${fastq}_2.fastq.gz" \
	    --riboseq_fq /path/to/the/directory/${LINE}_riboseq_fastq \
	    --star_idx_dir /path/to/the/directory/STAR_index/StarIndex \
	    --rnaUnstranded  true \
	    --transcript_fa /path/to/the/directory/annotation_fasta/cds.fa \
	    --offset offset.txt \
	    --sailfish_dir /path/to/the/directory/salmon_output/${LINE} \
	    --work_dir /path/to/the/directory/orqas_output/${LINE} \
	    --cds_range extracted_cds_ranges.txt &

     	# Check the number of running jobs
	running_jobs=$(jobs -p | wc -l)

	# Wait if the number of jobs reaches max_jobs
	while [ $running_jobs -ge $max_jobs ]; do
	     sleep 1
	     running_jobs=$(jobs -p | wc -l)
	done	
done  < $FILENAME

wait
	

#----------------------------------------------------------------------------
# Note:
# - extracted_cds_ranges.txt: generated by make_cds-range-file.py.
#   This file includes the CDS regions of transcripts needed for ribomap.
# - offset.txt: Contains offsets for read alignment. For further details,
#   visit the ribomap GitHub page:
#   https://github.com/Kingsford-Group/ribomap/blob/master/scripts/offset.txt
#----------------------------------------------------------------------------

